# Generated by Django 3.1.6 on 2021-02-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discoutn_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
