# Generated by Django 3.1.6 on 2021-02-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discoutn_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discoutn_price',
            new_name='discount_price',
        ),
    ]
